apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: atelier-dev

resources:
  - ../../base
  - configmap.yaml
  - secret.yaml

images:
  - name: atelier-kubernetes
    newTag: 1.0.0

patches:
  - path: patch-deployment.yaml
